timezone: Asia/Shanghai
encoding: UTF-8

markdown: redcarpet
exclude: [Rakefile, README.md]
lsi: true
redcarpet:
  extensions:
    - tables
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
